version: '2'
services:
    web:
      image: nginx:latest
      container_name: web
      ports:
        - "8000:80"
      volumes:
        - ./src/:/usr/share/nginx/html/
        - ./site.conf:/etc/nginx/conf.d/site.conf
      links:
        - php
    db:
        image: mysql:5.7
        container_name: database
        command: mysqld --sql_mode=""
        volumes:
            - ./mysql-db:/var/lib/mysql
            #- ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_ROOT_PASSWORD: password123
        ports:
            - '3308:3306'
    php:
      build:
        context: ./php-fpm
      container_name: php-fpm
      volumes:
        - ./php.ini:/usr/local/etc/php/conf.d/php.ini
        - ./src/:/usr/share/nginx/html/
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      ports:
         - 8080:80
      links:
         - db
         - web

